### ISSUE TITLE
annotations causing xml_dataclasses.exceptions.XmlTypeError

### ISSUE THREAD

**Issue by bphunter1972** [tobywf/xml_dataclasses#13]
Here's a puzzler...and maybe shows my inexperience with mixing Python3.7 and 3.8.

Take the following code, clearly lifted from the examples:

```python
# from __future__ import annotations
from dataclasses import dataclass
from typing import List
from lxml import etree  # type: ignore
from xml_dataclasses import xml_dataclass, dump, XmlDataclass

@xml_dataclass
@dataclass
class Test:
    __ns__ = None
    name: str
    severity: str = "DISABLED"

@xml_dataclass
@dataclass
class TestList(XmlDataclass):
    __ns__ = None
    tests: List[Test]

if __name__ == "__main__":
    tests = [Test(name="TESTING1"), Test(name="TESTING2"), Test(name="Testing3")]
    test_list = TestList(tests=tests)
    lxml_el_out = dump(test_list, "tests", None)
    print(etree.tostring(lxml_el_out, encoding="unicode", pretty_print=True))
```

Running this with python3.8 gives me this:
```
<tests>
  <tests name="TESTING1" severity="DISABLED"/>
  <tests name="TESTING2" severity="DISABLED"/>
  <tests name="Testing3" severity="DISABLED"/>
</tests>
```

Perfect. Now, uncomment line 1 to import annotations and re-run:

```
Traceback (most recent call last):
  File "////xml_dataclasses/src/xml_dataclasses/resolve_types.py", line 214, in _resolve_field_type
    types, is_list, namespace = _resolve_child_type(tp)
  File "////xml_dataclasses/src/xml_dataclasses/resolve_types.py", line 190, in _resolve_child_type
    raise XmlTypeError(msg)
xml_dataclasses.exceptions.XmlTypeError: Child type must be XML dataclass ('str'). (If you wanted an attribute, this must be an optional or required string)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "functional/annotations_test.py", line 11, in <module>
    class Test:
  File "////xml_dataclasses/src/xml_dataclasses/resolve_types.py", line 266, in xml_dataclass
    field_info = _resolve_field_type(f)
  File "////xml_dataclasses/src/xml_dataclasses/resolve_types.py", line 218, in _resolve_field_type
    raise XmlTypeError(msg) from e
xml_dataclasses.exceptions.XmlTypeError: Invalid type 'str' on field 'name'. Child type must be XML dataclass ('str'). (If you wanted an attribute, this must be an optional or required string)
```

This is pretty odd, (and not really in the spirit of type-annotations which should not affect the code). If I remove the List import and change to list, which is what I would do in my 3.8 world, I still get the same issue.

**Comment by tobywf** [comment]
> This is pretty odd, (and not really in the spirit of type-annotations which should not affect the code).

It isn't that odd, see e.g. [Python issue 39442](https://bugs.python.org/issue39442). Here's a minimal working example showing the issue:

```python
from __future__ import annotations
from dataclasses import dataclass
from xml_dataclasses import xml_dataclass, dump, XmlDataclass

@xml_dataclass
@dataclass
class Test(XmlDataclass):
    __ns__ = None
    name: str
```

Which is roughly equivalent to:

```python
from dataclasses import dataclass
from xml_dataclasses import xml_dataclass, dump, XmlDataclass

@xml_dataclass
@dataclass
class Test(XmlDataclass):
    __ns__ = None
    name: 'str'
```

The offending line: https://github.com/tobywf/xml_dataclasses/blob/30a233defa94c24ead5866c16106719969c5d5d4/src/xml_dataclasses/resolve_types.py#L204

Basically, `f.type` with postponed annotations is `'str'` (i.e. the string "str", and no longer the type `str`), so that's the source of the issue. This library probably needs to start calling something like [`typing.get_type_hints`](https://docs.python.org/3/library/typing.html#typing.get_type_hints) to resolve type hints. However, this can get quite complicated, e.g. see Pydantic's logic [to resolve types](https://github.com/samuelcolvin/pydantic/blob/d7a8272d7e0c151b0bd43df596be02e0d436ebdf/pydantic/typing.py).

**Comment by PeterSR** [comment]
We are experiencing a very similar problem with recursive dataclasses:

```python
from dataclasses import dataclass
from xml_dataclasses import xml_dataclass, XmlDataclass
from typing import Optional, List


@xml_dataclass
@dataclass
class A(XmlDataclass):
    __ns__ = "..."

    children: Optional[List["A"]]  # Or simply A if importing annotations from __future__.
```

Output:

```
Traceback (most recent call last):
  File ".../xml_dataclasses/resolve_types.py", line 214, in _resolve_field_type
    types, is_list, namespace = _resolve_child_type(tp)
  File ".../xml_dataclasses/resolve_types.py", line 190, in _resolve_child_type
    raise XmlTypeError(msg)
xml_dataclasses.exceptions.XmlTypeError: Child type must be XML dataclass (ForwardRef('A')). (If you wanted an attribute, this must be an optional or required string)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 8, in <module>
    class A(XmlDataclass):
  File ".../xml_dataclasses/resolve_types.py", line 266, in xml_dataclass
    field_info = _resolve_field_type(f)
  File ".../xml_dataclasses/resolve_types.py", line 218, in _resolve_field_type
    raise XmlTypeError(msg) from e
xml_dataclasses.exceptions.XmlTypeError: Invalid type 'typing.Union[typing.List[ForwardRef('A')], NoneType]' on field 'children'. Child type must be XML dataclass (ForwardRef('A')). (If you wanted an attribute, this must be an optional or required string)
```

Do you have any proposed fix or workaround?

**Comment by tobywf** [comment]
I proposed a fix earlier in the thread. I have now implemented that on the main branch. Please see if that fixes it. The fix isn't available via PyPI yet.

As a reminder: "covered Software is provided under this License on an "as is" basis". Basically, I don't have the time to maintain this library. This is compounded because I have moved on from Python and barely do any Python development any more.

If you would like to help, great. You may also want to start evaluating other options, in case future Python updates or features break this library again.

**Comment by PeterSR** [comment]
I completely understand. Thank you for your work @tobywf.
